package com.compliance.platform.remediator;

import java.util.UUID;

/**
 * A remediation plan generated by {@link RemediatorAgent} for a single violation.
 *
 * <p>Persisted to the {@code remediation_plans} table. Intentionally never auto-executed —
 * the {@code approvalStatus} gate is an architectural safety decision: a human must
 * approve before any fix is considered authorised, even for {@code autoRemediable} plans.
 *
 * @param autoRemediable true when the fix is a single deterministic AWS API call with
 *                       no risk of data loss or service disruption (e.g. rotate access key,
 *                       disable public bucket ACL). False for anything requiring architectural
 *                       judgment (network topology, IAM policy redesign, app-level changes).
 */
public record RemediationPlan(
        UUID   id,
        UUID   violationId,
        String steps,           // numbered, human-readable steps
        String cliCommands,     // AWS CLI commands, one per line (nullable)
        String terraformPatch,  // corrected Terraform resource block (nullable)
        boolean autoRemediable,
        String approvalStatus   // PENDING | APPROVED | REJECTED
) {}
