#!/usr/bin/env bash
# fetch-secrets.sh — pull production secrets from AWS Secrets Manager and write .env.prod
#
# Prerequisites:
#   - AWS CLI configured (instance role or explicit credentials)
#   - Secret named "compliance/prod" in Secrets Manager containing a JSON object with keys:
#       ANTHROPIC_API_KEY, POSTGRES_PASSWORD, AWS_SES_FROM_EMAIL, SNS_ALERT_TOPIC_ARN, etc.
#
# Usage:
#   ./scripts/fetch-secrets.sh [secret-name] [aws-region]
#
# Defaults:
#   secret-name = compliance/prod
#   aws-region  = us-east-1

set -euo pipefail

SECRET_NAME="${1:-compliance/prod}"
AWS_REGION="${2:-us-east-1}"
OUTPUT_FILE="$(dirname "$0")/../.env.prod"

echo "Fetching secrets from AWS Secrets Manager..."
echo "  Secret:  $SECRET_NAME"
echo "  Region:  $AWS_REGION"

# Fetch the secret JSON
SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "$SECRET_NAME" \
    --region "$AWS_REGION" \
    --query SecretString \
    --output text)

if [ -z "$SECRET_JSON" ]; then
    echo "ERROR: Secret '$SECRET_NAME' returned empty value." >&2
    exit 1
fi

# Write each key=value pair to .env.prod
# Expects a flat JSON object: {"KEY": "value", ...}
echo "# Generated by fetch-secrets.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$OUTPUT_FILE"
echo "# DO NOT COMMIT this file." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "$SECRET_JSON" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for k, v in data.items():
    # Wrap value in quotes; escape any existing double quotes
    v_escaped = str(v).replace('\"', '\\\\\"')
    print(f'{k}=\"{v_escaped}\"')
" >> "$OUTPUT_FILE"

# Append non-secret configuration that isn't sensitive
cat >> "$OUTPUT_FILE" << 'EOF'

# Non-secret config — safe to set here
POSTGRES_DB=compliance
POSTGRES_USER=compliance
AWS_REGION=us-east-1
SPRING_PROFILES_ACTIVE=prod
EOF

chmod 600 "$OUTPUT_FILE"
echo "Written to $OUTPUT_FILE (mode 600)"
